{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebasemessaging",
    "module": "firebase_messaging_debug",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_messaging_debug-0.0.1.aar",
          "url": "firebase_messaging_debug-0.0.1.aar",
          "size": 52656,
          "sha512": "b45f1ddfd50ea19306b697767260437956be2c5d578a50f9cc838f46b4a07667f2e59c119b28c7ed030b011d748513e1d9494cb566e69127da7be15f0f81b68b",
          "sha256": "a65e4bba37ecceec5bc9df38390a17d111d4c767673980554ec4c05bad0c2d68",
          "sha1": "3f3eec89d9c7438343eee2afbebd2f29b67f11ab",
          "md5": "6a0dfc8d2b3ddc7a0097eb570304ead6"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "33.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_messaging_debug-0.0.1.aar",
          "url": "firebase_messaging_debug-0.0.1.aar",
          "size": 52656,
          "sha512": "b45f1ddfd50ea19306b697767260437956be2c5d578a50f9cc838f46b4a07667f2e59c119b28c7ed030b011d748513e1d9494cb566e69127da7be15f0f81b68b",
          "sha256": "a65e4bba37ecceec5bc9df38390a17d111d4c767673980554ec4c05bad0c2d68",
          "sha1": "3f3eec89d9c7438343eee2afbebd2f29b67f11ab",
          "md5": "6a0dfc8d2b3ddc7a0097eb570304ead6"
        }
      ]
    }
  ]
}
