{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.crashlytics",
    "module": "firebase_crashlytics_debug",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_crashlytics_debug-0.0.1.aar",
          "url": "firebase_crashlytics_debug-0.0.1.aar",
          "size": 17373,
          "sha512": "15240a4d65f9f626f22c8ee2ec7d34622bdd282ff0f262f25c2c9575acd84213999eec43374311a6bf6a0f8c9a9c79d6f7125841905234e7e7fb27eda6dff675",
          "sha256": "110c0b49cd4155106989f42f624f2f0dbd0a6d81d82b578ba49ba1ba7271b117",
          "sha1": "525b51dce3d92f24369a9a1224713bc8292af284",
          "md5": "bf29ce2208feb23b043c9d668ea1e754"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "33.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_crashlytics_debug-0.0.1.aar",
          "url": "firebase_crashlytics_debug-0.0.1.aar",
          "size": 17373,
          "sha512": "15240a4d65f9f626f22c8ee2ec7d34622bdd282ff0f262f25c2c9575acd84213999eec43374311a6bf6a0f8c9a9c79d6f7125841905234e7e7fb27eda6dff675",
          "sha256": "110c0b49cd4155106989f42f624f2f0dbd0a6d81d82b578ba49ba1ba7271b117",
          "sha1": "525b51dce3d92f24369a9a1224713bc8292af284",
          "md5": "bf29ce2208feb23b043c9d668ea1e754"
        }
      ]
    }
  ]
}
