{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_debug",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_debug-0.0.1.aar",
          "url": "flutter_secure_storage_debug-0.0.1.aar",
          "size": 27884,
          "sha512": "e90011a08c0b1c0b60b7587f403e5990d060b77a4515e5d4fef66832c26c3a316e3b01e3a7b71b0d71fe2da584b70502261943530d5262ae1e8f69bea3409553",
          "sha256": "fed4030f58eaffa340b993e61c8e0214ecd1898efcca14595e5118a8519c6d72",
          "sha1": "ab9ab2180aa02ee68170871c6b0910ff4316f49c",
          "md5": "e0ea99ebeb411006d116602a8cab3a9a"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_debug-0.0.1.aar",
          "url": "flutter_secure_storage_debug-0.0.1.aar",
          "size": 27884,
          "sha512": "e90011a08c0b1c0b60b7587f403e5990d060b77a4515e5d4fef66832c26c3a316e3b01e3a7b71b0d71fe2da584b70502261943530d5262ae1e8f69bea3409553",
          "sha256": "fed4030f58eaffa340b993e61c8e0214ecd1898efcca14595e5118a8519c6d72",
          "sha1": "ab9ab2180aa02ee68170871c6b0910ff4316f49c",
          "md5": "e0ea99ebeb411006d116602a8cab3a9a"
        }
      ]
    }
  ]
}
