{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_debug",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-0.0.1.aar",
          "url": "shared_preferences_android_debug-0.0.1.aar",
          "size": 97848,
          "sha512": "5c1cabb63425958d0eb6879a98f6c2c62f75708ff3b1caa1adfeabe41c731b2fd2ae6128d4758cda2b56a99d7796d2d9d4aab3b235d85af8b54799f2297a832b",
          "sha256": "85a35f0d7d3e4df9b2c373135a402dcc2c8b57371b498cec0109e65f4890dc7c",
          "sha1": "b5ac221dec2f51922d97cd08316fa9ded1339598",
          "md5": "5bb76ae391b1f86b902a3e0938b1f7d4"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-0.0.1.aar",
          "url": "shared_preferences_android_debug-0.0.1.aar",
          "size": 97848,
          "sha512": "5c1cabb63425958d0eb6879a98f6c2c62f75708ff3b1caa1adfeabe41c731b2fd2ae6128d4758cda2b56a99d7796d2d9d4aab3b235d85af8b54799f2297a832b",
          "sha256": "85a35f0d7d3e4df9b2c373135a402dcc2c8b57371b498cec0109e65f4890dc7c",
          "sha1": "b5ac221dec2f51922d97cd08316fa9ded1339598",
          "md5": "5bb76ae391b1f86b902a3e0938b1f7d4"
        }
      ]
    }
  ]
}
