{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aboutyou.dart_packages.sign_in_with_apple",
    "module": "sign_in_with_apple_debug",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        }
      ],
      "files": [
        {
          "name": "sign_in_with_apple_debug-0.0.1.aar",
          "url": "sign_in_with_apple_debug-0.0.1.aar",
          "size": 11403,
          "sha512": "9512dd8c12067d38380c9ccfca2ec70b1023c96772d222a3d0cb8647a3a195723aeac7cb4825c326328ef24b79a3ad1e54049e73b08eb0ce84b2b828419258e3",
          "sha256": "a74a40374683514361eef8c9b16e5ef31cf800c38c96d91589cbad28215e4f0a",
          "sha1": "bb2e363505a1981077b5bc4497e6996c3c54054f",
          "md5": "efc4475fd5384e1693bf64d98e0e45e5"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "sign_in_with_apple_debug-0.0.1.aar",
          "url": "sign_in_with_apple_debug-0.0.1.aar",
          "size": 11403,
          "sha512": "9512dd8c12067d38380c9ccfca2ec70b1023c96772d222a3d0cb8647a3a195723aeac7cb4825c326328ef24b79a3ad1e54049e73b08eb0ce84b2b828419258e3",
          "sha256": "a74a40374683514361eef8c9b16e5ef31cf800c38c96d91589cbad28215e4f0a",
          "sha1": "bb2e363505a1981077b5bc4497e6996c3c54054f",
          "md5": "efc4475fd5384e1693bf64d98e0e45e5"
        }
      ]
    }
  ]
}
